### ISSUE TITLE
New DevOps/SRE Folder

### ISSUE THREAD

**Issue by BasharDlaleh** [joinimagine/imagine_home_assignments#3]
please create a new folder in the repo for DevOps/SRE engineers, I also suggest that instead of you adding a task and fellows solve it, let the fellows add the tasks that were assigned to them in their previous tech interviews with real employers so we can benefit from each other's experiences.

**Comment by bassem-i** [comment]
Hey @BasharDlaleh, Please feel free to create a PR with tasks for DevOps/SRE engineers 🙏

**Comment by bassem-i** [comment]
Hey, The PR have been merged! Thanks alot!
